sudo: required

services:
  - docker

before_install:
  - docker pull centos:7

script:
  - docker build -t philippwinter/clr:latest .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push philippwinter/clr:latest;
    fi